version: '3.8'

services:
  django:
    image: college_registration_form_project-django
    build: ./courses_api
    command: gunicorn courses_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./courses_api:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - postgres_network

  postgres:
    image: postgres:15  # Use the same version as the data directory
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
