# Generated by Django 4.2.15 on 2024-08-27 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='DEFAULT_CODE', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='semester',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
